### ISSUE TITLE
Improve the website ui

### ISSUE THREAD

**Issue by condef5** [condef5/freecodecamp-scraping#1]
Improve the presentation of the score of the participants of the top freecodecamp.

**Comment by rasfa98** [comment]
Any ideas for the new presentation? Should only the top scores change?

**Comment by condef5** [comment]
You could show users as a grid: from the first place to the last.
![meme](http://pm1.narvii.com/6239/3345b770ccd19e2f8a70015a3bf775c8dbb4b3c8_00.jpg).

**Comment by rasfa98** [comment]
Good idea, I will see if I can come up with something nice 😄
